development:
  sessions:
    default:
      database: mindsweeper_test
      hosts: 
      - localhost

development:
  sessions:
    default:
      database: mindsweeper_dev
      hosts: 
      - localhost

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
